Add missing #include <sys/sysmacros.h>
This header is required to use functions makedev(), major() and minor() with new
glibc. Absence of this header leads to link time errors like "undefined
reference to function minor" or compile time errors like:

mksquashfs.c:991:24: error: called object 'major' is not a function or function pointer
  991 |   unsigned int major = major(buf->st_rdev);
      |                        ^~~~~

unsquashfs.c: In function 'create_inode':
unsquashfs.c:1132:7: warning: implicit declaration of function 'makedev' [-Wimplicit-function-declaration]
 1132 |       makedev((i->data >> 8) & 0xff,
      |       ^~~~~~~

git-svn-id: http://192.168.42.160/software/work_branches/PORTF-363@27524 ce24552a-085e-4656-8849-d4bfd34db3c6