Add missing stime() implementation.
stime() has been removed from glibc since version 2.31, so attempts to use it
lead to linker errors: undefined reference to stime.

git-svn-id: http://192.168.42.160/software/work_branches/PORTF-363@27526 ce24552a-085e-4656-8849-d4bfd34db3c6